### ISSUE TITLE
api/info がステータス500を返す

### ISSUE THREAD

**Issue by tnakai11** [seal-git/22zemi#301]
main をマージした開発ブランチで発生中の問題です。
仕様上セッション開始時は init、invite、info の順にAPIを叩くのが自然な流れだと判断しそのように実装しているところなのですが、init、invite までは ステータス200が返るものの info はステータス 500が返ってきます。

以下が init、invite、info の順に叩いた時のログです。

> 172.18.0.5 - - [01/Nov/2021 04:48:26] "POST /init HTTP/1.1" 200 -
> 172.18.0.5 - - [01/Nov/2021 04:48:26] "POST /invite HTTP/1.1" 200 -
> { 'genre': '',
>   'group_id': '698532',
>   'open_hour': 13,
>   'open_hour_str': '13:48',
>   'place': '新宿',
>   'user_id': '223955'}
> new user 223955 registered
> new group 698532 registered
> set_filter_params: params renewed
> yahoo_local_search with params
> 12:00:00
> get_restaurants_info: 6 items
> find place: 新宿ビアガーデン ALOHA FLAMES アロハフレイムス
> find place: 個室ダイニング 光屋‐HIKARIYA‐ 渋谷本店
> find place: 青山セントグレース大聖堂
> find place: 個室居酒屋 隠れ野 渋谷店
> find place: 池袋 寿司 空
> find place: マーブルラウンジ
> Exception in thread Thread-28:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
> Exception in thread Thread-25:
> Exception in thread Thread-27:
> Traceback (most recent call last):
> Exception in thread Thread-23:
>     self.run()
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
>   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/threading.py", line 910, in run
>   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
>     self._target(*self._args, **self._kwargs)
> Exception in thread Thread-26:
> Traceback (most recent call last):
>     self.run()
>   File "/usr/local/lib/python3.9/threading.py", line 910, in run
>   File "/workspace/app/call_api.py", line 152, in thread_get_restaurant_info
>   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.9/threading.py", line 910, in run
> Exception in thread Thread-24:
>     self._target(*self._args, **self._kwargs)
>     self.run()
>     self._target(*self._args, **self._kwargs)
>   File "/workspace/app/call_api.py", line 152, in thread_get_restaurant_info
>   File "/workspace/app/call_api.py", line 152, in thread_get_restaurant_info
>     self.run()
>   File "/usr/local/lib/python3.9/threading.py", line 910, in run
>   File "/usr/local/lib/python3.9/threading.py", line 910, in run
> Traceback (most recent call last):
>     self._target(*self._args, **self._kwargs)
>     self._target(*self._args, **self._kwargs)
>   File "/workspace/app/call_api.py", line 152, in thread_get_restaurant_info
>   File "/workspace/app/call_api.py", line 152, in thread_get_restaurant_info
>   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
>     r_info = api_functions.yahoo_review(r_info)
>   File "/workspace/app/api_functions.py", line 34, in yahoo_review
>     self.run()
>     r_info = api_functions.yahoo_review(r_info)
>   File "/usr/local/lib/python3.9/threading.py", line 910, in run
>   File "/workspace/app/api_functions.py", line 34, in yahoo_review
>     r_info = api_functions.yahoo_review(r_info)
>     r_info = api_functions.yahoo_review(r_info)
>   File "/workspace/app/api_functions.py", line 34, in yahoo_review
>     self._target(*self._args, **self._kwargs)
>     r_info = api_functions.yahoo_review(r_info)
>   File "/workspace/app/call_api.py", line 152, in thread_get_restaurant_info
>   File "/workspace/app/api_functions.py", line 34, in yahoo_review
>   File "/workspace/app/api_functions.py", line 34, in yahoo_review
>     review_list = response["Feature"]
> KeyError: 'Feature'
>     review_list = response["Feature"]
> KeyError: 'Feature'
>     review_list = response["Feature"]
> KeyError: 'Feature'
>     review_list = response["Feature"]
>     review_list = response["Feature"]
> KeyError: 'Feature'
> KeyError: 'Feature'
>     r_info = api_functions.yahoo_review(r_info)
>   File "/workspace/app/api_functions.py", line 34, in yahoo_review
>     review_list = response["Feature"]
> KeyError: 'Feature'
> 172.18.0.5 - - [01/Nov/2021 04:48:27] "POST /info HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2464, in _call_
>     return self.wsgi_app(environ, start_response)
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
>     response = self.handle_exception(e)
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/workspace/app/models.py", line 246, in http_info
>     _ = recommend.recommend_main(fetch_group, group_id, user_id,
>   File "/workspace/app/recommend.py", line 904, in recommend_main
>     first_time_recommend_main(fetch_group, group_id, user_id, recomm)
>   File "/workspace/app/recommend.py", line 1024, in first_time_recommend_main
>     restaurants_info = call_api.get_restaurants_info(fetch_group,
>   File "/workspace/app/call_api.py", line 125, in get_restaurants_info
>     restaurants_info = calc_info.add_votes(fetch_group,
>   File "/workspace/app/calc_info.py", line 38, in add_votes
>     History.restaurant==restaurants_info[i].id,
> AttributeError: 'NoneType' object has no attribute 'id'

**Comment by seal-git** [comment]
resolved at #302
