### ISSUE TITLE
API: /init の仕様

### ISSUE THREAD

**Issue by tnakai11** [seal-git/22zemi#312]
招待URL経由で Reskima にアクセスした場合

- group_id: URLより決定済み
- user_id: APIから要取得

という状態になるため /init について
group_id を指定して user_id をリクエストするオプションがあると助かります。
reponse のフォーマットは現状と同じで問題ないです。

**Comment by seal-git** [comment]
initでもらえるgroup_idはinfoで投げるまで登録されないので、フロントで捨ててください
